--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MrEcstsy/MartianUtilities
build-by-default: true
branches:
- main
projects:
  MartianUtilities:
    path: ""
    model: virion
    type: library
...
